twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        repositorio_tareas: '@App\Repository\TareaRepository'
        formato_fecha: '%app.formato_fecha%'
        listado_idiomas: '%app.listado_idiomas%'